**

!apps/
!apps/spa-dev/
!apps/spa-dev/package.json
!apps/spa-dev/package-lock.json
!apps/spa-dev/index.html
!apps/spa-dev/eslint.config.js
!apps/spa-dev/postcss.config.js
!apps/spa-dev/quasar.config.ts
!apps/spa-dev/tsconfig.json
!apps/spa-dev/public/
!apps/spa-dev/public/**
!apps/spa-dev/src/
!apps/spa-dev/src/**

!deploy/
!deploy/docker/
!deploy/docker/spa-dev/
!deploy/docker/spa-dev/**
