**

!apps/
!apps/spa-dslab/
!apps/spa-dslab/package.json
!apps/spa-dslab/package-lock.json
!apps/spa-dslab/index.html
!apps/spa-dslab/eslint.config.js
!apps/spa-dslab/postcss.config.js
!apps/spa-dslab/quasar.config.ts
!apps/spa-dslab/tsconfig.json
!apps/spa-dslab/public/
!apps/spa-dslab/public/**
!apps/spa-dslab/src/
!apps/spa-dslab/src/**

!deploy/
!deploy/docker/
!deploy/docker/spa-dslab/
!deploy/docker/spa-dslab/**
