services:
  api:
    volumes:
      - type: bind
        source: ${QUICKQUIZ_SECRETS_ROOT:?set QUICKQUIZ_SECRETS_ROOT}/api
        target: /run/secrets
        read_only: true
        bind:
          create_host_path: false

  ads-api:
    volumes:
      - type: bind
        source: ${QUICKQUIZ_SECRETS_ROOT:?set QUICKQUIZ_SECRETS_ROOT}/ads-api
        target: /run/secrets
        read_only: true
        bind:
          create_host_path: false

  redis:
    volumes:
      - type: bind
        source: ${QUICKQUIZ_SECRETS_ROOT:?set QUICKQUIZ_SECRETS_ROOT}/redis
        target: /run/secrets
        read_only: true
        bind:
          create_host_path: false

  manager-db:
    volumes:
      - type: bind
        source: ${QUICKQUIZ_SECRETS_ROOT:?set QUICKQUIZ_SECRETS_ROOT}/manager-db
        target: /run/secrets
        read_only: true
        bind:
          create_host_path: false

  manager-fpm:
    volumes:
      - type: bind
        source: ${QUICKQUIZ_SECRETS_ROOT:?set QUICKQUIZ_SECRETS_ROOT}/manager
        target: /run/secrets
        read_only: true
        bind:
          create_host_path: false
