**

!apps/
!apps/manager/
!apps/manager/composer.json
!apps/manager/composer.lock
!apps/manager/importmap.php
!apps/manager/assets/
!apps/manager/assets/**
!apps/manager/bin/
!apps/manager/bin/**
!apps/manager/config/
!apps/manager/config/**
!apps/manager/public/
!apps/manager/public/**
!apps/manager/src/
!apps/manager/src/**
!apps/manager/templates/
!apps/manager/templates/**

!deploy/
!deploy/docker/
!deploy/docker/manager/
!deploy/docker/manager/**
