expose_php = Off
memory_limit = ${MANAGER_PHP_MEMORY_LIMIT}
post_max_size = ${MANAGER_PHP_POST_MAX_SIZE}
upload_max_filesize = ${MANAGER_PHP_UPLOAD_MAX_FILESIZE}
realpath_cache_size = 4096K
realpath_cache_ttl = 600
session.cookie_httponly = 1
session.cookie_samesite = Lax
opcache.enable = 1
opcache.enable_cli = 0
opcache.validate_timestamps = 0
opcache.memory_consumption = ${MANAGER_PHP_OPCACHE_MEMORY}
opcache.interned_strings_buffer = 12
opcache.max_accelerated_files = 12000
